name: Build and Deploy Go Lambda

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.23 # Specify your Go version

    - name: Install Dependencies
      run: |
        go mod tidy

    - name: Build Lambda Binary
      run: |
        GOOS=linux GOARCH=arm64 go build -tags lambda.norpc -o bootstrap

    - name: Zip Binary
      run: zip function.zip bootstrap

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1 # Change to your preferred region

    - name: Deploy to AWS Lambda
      run: |
        aws lambda update-function-code \
          --function-name cmc-scan-analyze \
          --zip-file fileb://function.zip

    - name: Clean Up
      run: |
        rm -f main function.zip
